
CREATE TABLE FORUM_POSTS(
POST_ID NUMBER,
CONSTRAINT POST_PK PRIMARY KEY (POST_ID),
SUBCATEGORY_ID NUMBER,
CONSTRAINT SUBCATEGORIES_FK FOREIGN KEY(SUBCATEGORY_ID) REFERENCES FORUM_SUBCATEGORIES(SUBCATEGORY_ID),
USER_ID NUMBER,
CONSTRAINT USERS_FK FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
OPTION_ID NUMBER,
CONSTRAINT OPTIONS_FK FOREIGN KEY(OPTION_ID) REFERENCES FORUM_POLLS_OPTIONS(OPTION_ID),
TITLE NVARCHAR2(90) NOT NULL,
POSTS_CONTENT CLOB,
IS_POLL NUMBER(1,0),
POST_DATE TIMESTAMP NOT NULL,
IP NVARCHAR2(20) NOT NULL
);