
CREATE TABLE FORUM_POLLS_OPTIONS_VOTES(
POOL_ID NUMBER,
CONSTRAINT POOLS_PK PRIMARY KEY (POOL_ID),
VOTES_USER_ID NUMBER,
CONSTRAINT VOTES_USER_FK FOREIGN KEY(VOTES_USER_ID) REFERENCES USERS(USER_ID),
POLL_OPTION_ID NUMBER,
CONSTRAINT POLL_OPTION_FK FOREIGN KEY(POLL_OPTION_ID) REFERENCES FORUM_POOLS_OPTIONS(OPTION_ID),
VOTE_DATE TIMESTAMP NOT NULL,
IP NVARCHAR2(20)NOT NULL
);