
CREATE TABLE FORUM_CATEGORIES(
CATEGORY_ID NUMBER,
CONSTRAINT CATEGORIES_PK PRIMARY KEY (CATEGORY_ID),
TITLE NVARCHAR2(64) NOT NULL,
DESCRIPTION CLOB,
CATEGORY_DATE TIMESTAMP NOT NULL,
IP NVARCHAR2(20) NOT NULL
);