
CREATE TABLE USERS(
USER_ID NUMBER,
CONSTRAINT USER_PK PRIMARY KEY (USER_ID),
NICK NVARCHAR2(16) UNIQUE,
PASSWORD NVARCHAR2(128) NOT NULL,
EMAIL NVARCHAR2(128) NOT NULL,
USER_DATE TIMESTAMP NOT NULL,
KARMA FLOAT(2) NOT NULL,
IP NVARCHAR2(20) NOT NULL
);