
CREATE TABLE FORUM_POOLS_OPTIONS(
OPTION_ID NUMBER,
CONSTRAINT OPTION_PK PRIMARY KEY (OPTION_ID),
POST_ID NUMBER,
CONSTRAINT POSTS_FK FOREIGN KEY(POST_ID) REFERENCES FORUM_POSTS(POST_ID),
TITLE NVARCHAR2(64) NOT NULL,
POST_DATE TIMESTAMP NOT NULL
);
