
CREATE TABLE FORUM_SUBCATEGORIES(
SUBCATEGORY_ID NUMBER,
CONSTRAINT SUBCATEGORY_PK PRIMARY KEY (SUBCATEGORY_ID),
CATEGORY_ID NUMBER,
CONSTRAINT CATEGORIES_FK FOREIGN KEY(CATEGORY_ID) REFERENCES FORUM_CATEGORIES(CATEGORY_ID),
TITLE NVARCHAR2(45) NOT NULL,
DESCRIPTION CLOB,
FORUM_DATE TIMESTAMP NOT NULL,
IP NVARCHAR2(20) NOT NULL
);
