
--ALTER TABLE TABLE_NAME
--ADD COLUMN_NAME TYPE ...

--ALTER TABLE TABLE_NAME
--DROP COLUMN COLUMN_NAME;

--ALTER TABLE TABLE_NAME
--MODIFY COLUMN_NAME TYPE ...

ALTER TABLE CUSTOMER
ADD AGE NUMBER;

ALTER TABLE CUSTOMER
DROP COLUMN REPORTS_TO, NOTES, PHOTO;

ALTER TABLE CUSTOMER
MODIFY CUSTNAME NVARCHAR2(90);

ALTER TABLE CUSTOMER
ADD AGE NUMBER DEFAULT 0 NOT NULL;

ALTER TABLE CUSTOMER
MODIFY SALESMAN_ID NOT NULL;