
CREATE TABLE CUSTOMER(
CUSTOMER_ID NUMBER PRIMARY KEY,
CUSTNAME NVARCHAR2(50) NOT NULL,
CITY NVARCHAR2(50) NOT NULL,
SALESMAN_ID NUMBER,
CONSTRAINT SALESMAN_FK FOREIGN KEY (SALESMAN_ID) REFERENCES SALESMAN(SALESMAN_ID)
);
INSERT INTO CUSTOMER VALUES(3002, 'Babay', 'ATHENS', 5001);
INSERT INTO CUSTOMER VALUES(3005, 'Coco', 'NY', 5002);
INSERT INTO CUSTOMER VALUES(3001, 'Soil', 'KIEV', 5005);
INSERT INTO CUSTOMER VALUES(3004, 'DedPool', 'BERLIN', 5006);
INSERT INTO CUSTOMER VALUES(3009, 'Egor', 'LONDON', 5003);
INSERT INTO CUSTOMER VALUES(3008, 'Fedor', 'PARIS', 5002);
INSERT INTO CUSTOMER VALUES(3007, 'Gogi', 'ATHENS', 5001);
INSERT INTO CUSTOMER VALUES(3006, 'Herb', 'NY', 5007);
INSERT INTO CUSTOMER VALUES(3003, 'Karl', 'MINSK', null);