
CREATE TABLE SALESMAN(
SALESMAN_ID NUMBER PRIMARY KEY,
NAME NVARCHAR2(50) NOT NULL,
CITY NVARCHAR2(50) NOT NULL,
COMMISSION NUMBER(*,2) DEFAULT '0.1'
);

CREATE TABLE CUSTOMER(
CUSTOMER_ID NUMBER PRIMARY KEY,
CUSTNAME NVARCHAR2(50) NOT NULL,
CITY NVARCHAR2(50) NOT NULL,
SALESMAN_ID NUMBER,
CONSTRAINT SALESMAN_FK FOREIGN KEY (SALESMAN_ID) REFERENCES SALESMAN(SALESMAN_ID)
);

DROP TABLE CUSTOMER;

INSERT INTO SALESMAN VALUES(5001, 'QQQQQ', 'NY', 0.15);
INSERT INTO SALESMAN VALUES(5002, 'WWWWW', 'PARIS', 0.12);
INSERT INTO SALESMAN VALUES(5003, 'EEEEE', 'LONDON', 0.1);
INSERT INTO SALESMAN VALUES(5004, 'RRRRR', 'PARIS', 0.14);
INSERT INTO SALESMAN VALUES(5005, 'TTTTT', 'KIEV', 0.14);
INSERT INTO SALESMAN VALUES(5006, 'YYYYY', 'MOSKOW', 0.12);
INSERT INTO SALESMAN VALUES(5007, 'UUUUU', 'NY', 0.13);
INSERT INTO SALESMAN VALUES(5008, 'IIIII', 'LONDON', 0.15);
INSERT INTO SALESMAN VALUES(5009, 'OOOOO', 'ATHENS', 0.1);


INSERT INTO CUSTOMER VALUES(3002, 'AAAA', 'ATHENS', 5001);
INSERT INTO CUSTOMER VALUES(3005, 'BBBB', 'NY', 5002);
INSERT INTO CUSTOMER VALUES(3001, 'CCCC', 'KIEV', 5005);
INSERT INTO CUSTOMER VALUES(3004, 'DDDD', 'BERLIN', 5006);
INSERT INTO CUSTOMER VALUES(3009, 'EEEE', 'LONDON', 5003);
INSERT INTO CUSTOMER VALUES(3008, 'FFFF', 'PARIS', 5002);
INSERT INTO CUSTOMER VALUES(3007, 'GGGG', 'ATHENS', 5001);
INSERT INTO CUSTOMER VALUES(3006, 'HHHH', 'NY', 5007);
INSERT INTO CUSTOMER VALUES(3003, 'IIII', 'MINSK', null);

SELECT * FROM SALESMAN;

SELECT * FROM SALESMAN, CUSTOMER;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME FROM SALESMAN, CUSTOMER;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME
FROM SALESMAN, CUSTOMER
WHERE SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.CITY = CUSTOMER.CITY;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME, SALESMAN.CITY
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.CITY = CUSTOMER.CITY;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME, SALESMAN.CITY
FROM SALESMAN
LEFT JOIN CUSTOMER ON SALESMAN.CITY = CUSTOMER.CITY;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME, SALESMAN.CITY
FROM SALESMAN
RIGHT JOIN CUSTOMER ON SALESMAN.CITY = CUSTOMER.CITY;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME, SALESMAN.CITY
FROM SALESMAN
FULL JOIN CUSTOMER ON SALESMAN.CITY = CUSTOMER.CITY;








































