

CREATE TABLE PRODUCTS(
PRODUCT_ID NUMBER,
CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID),
PRODUCT_NAME NVARCHAR2(100) UNIQUE,
SUPPLIER_ID NUMBER,
CONSTRAINT SUPPLIER_FK FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
CATEGORY_ID NUMBER,
CONSTRAINT CATEGORY_FK FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
QUANTITY_PER_UNIT NUMBER NOT NULL,
UNIT_PRICE NUMBER NOT NULL,
UNIT_ON_STOCK NUMBER NOT NULL,
UNIT_ON_ORDER NUMBER NOT NULL,
REORDER_LEVEL NUMBER NOT NULL,
DISCONTINUED NUMBER NOT NULL
);