
CREATE TABLE CATEGORIES(
CATEGORY_ID NUMBER,
CONSTRAINT CATEGORY_PK PRIMARY KEY (CATEGORY_ID),
CATEGORY_NAME NVARCHAR2(50) UNIQUE,
DESCRIPTION NVARCHAR2(100) NOT NULL,
PICTURE NVARCHAR2(100) NOT NULL
-- не знаю ничего о пикчерс
);