
CREATE TABLE SUPPLIERS(
SUPPLIER_ID NUMBER,
CONSTRAINT SUPPLIER_PK PRIMARY KEY (SUPPLIER_ID),
COMPANY_NAME NVARCHAR2(50) UNIQUE,
CONTACT_NAME NVARCHAR2(50) NOT NULL,
CONTACT_TITLE NVARCHAR2(100) NOT NULL,
ADDRESS NVARCHAR2(50) NOT NULL,
CITY NVARCHAR2(50) NOT NULL,
REGION NVARCHAR2(50) NOT NULL,
POSTAL_CODE NUMBER NOT NULL,
COUNTRY NVARCHAR2(50) NOT NULL,
PHONE NUMBER NOT NULL,
FAX NUMBER NOT NULL,
HOME_PAGE NVARCHAR2(50) UNIQUE
);