
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER,
CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID),
LAST_NAME NVARCHAR2(50) NOT NULL,
FIRST_NAME NVARCHAR2(50) NOT NULL,
TITLE NVARCHAR2(100) NOT NULL,
TITLE_OF_COURTESY NVARCHAR2(100) NOT NULL,
BIRTH_DATE TIMESTAMP NOT NULL,
HIRE_DATE TIMESTAMP NOT NULL,
ADDRESS NVARCHAR2(50) NOT NULL,
CITY NVARCHAR2(50) NOT NULL,
REGION NVARCHAR2(50) NOT NULL,
POSTAL_CODE NUMBER NOT NULL,
SHIP_COUNTRY NVARCHAR2(50) NOT NULL,
HOME_PHONE NUMBER NOT NULL,
EXTENSION NUMBER NOT NULL,
PHOTO NVARCHAR2(50) NOT NULL,
-- не знаю ничего о фото
NOTES NVARCHAR2(100) UNIQUE,
REPORTS_TO NVARCHAR2(100) UNIQUE
);
