
CREATE TABLE ORDER_DETAILS(
ORDER_ID NUMBER,
CONSTRAINT ORDER_FK FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
PRODUCT_ID NUMBER,
CONSTRAINT PRODUCT_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
UNIT_PRICE NUMBER NOT NULL,
QUANTITY NUMBER NOT NULL,
DISCOUNT NUMBER NOT NULL
);