
CREATE TABLE ORDERS(
ORDER_ID NUMBER,
CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_ID),
CUSTOMER_ID NUMBER,
CONSTRAINT CUSTOMER_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
EMPLOYEE_ID NUMBER,
CONSTRAINT EMPLOYEE_FK FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
SHIPPER_ID NUMBER,
CONSTRAINT SHIPPER_FK FOREIGN KEY(SHIPPER_ID) REFERENCES SHIPPERS(SHIPPER_ID),
ORDER_DATE TIMESTAMP NOT NULL,
REQUIRED_DATE TIMESTAMP NOT NULL,
SHIPPED_DATE TIMESTAMP NOT NULL,
SHIP_VIA NVARCHAR2(50) NOT NULL,
FREIGHT NUMBER NOT NULL,
SHIP_NAME NVARCHAR2(50) NOT NULL,
SHIP_ADDRESS NVARCHAR2(50) NOT NULL,
SHIP_CITY NVARCHAR2(50) NOT NULL,
SHIP_REGION NVARCHAR2(50) NOT NULL,
SHIP_POSTAL_CODE NUMBER NOT NULL,
SHIP_COUNTRY NVARCHAR2(50) NOT NULL
);
