CREATE TABLE AUTHOR(
ID NUMBER,
CONSTRAINT AUTHOR_PK PRIMARY KEY (ID),
--CONSTRAINT CONST-NAME CONSTRAINT TYPE(COLUMN NAME)
NAME NVARCHAR2(50) NOT NULL,
LAST_NAME NVARCHAR2(50) UNIQUE,
COUNTRY NVARCHAR2(50) DEFAULT 'ENGLAND',
AGE NUMBER DEFAULT 0,
ARTICLES_COUNT NUMBER CHECK(ARTICLES_COUNT >10),
CONSTRAINT CHECK(COUNTRY != 'CHINA' AND LAST_NAME != 'TEST_LN')
);

CREATE TABLE HOTEL (
ID NUMBER,
CONSTRAINT TABLE_ID PRIMARY KEY(ID),
COUNTRY NVARCHAR2(50) DEFAULT 'N/A',
CITY NVARCHAR2(50) NOT NULL,
STREET NVARCHAR2(50),
CONSTRAINT CHECK_COUNT CHECK (COUNTRY !='Romania' AND COUNTRY != 'Belgium' AND COUNTRY != 'China' AND COUNTRY != 'Ukraine')
);

CREATE TABLE ORDER (
ID NUMBER,
CONSTRAINT ORD_ID PRIMARY KEY (ID),
USER_ID NVARCHAR2(50) UNIQUE,
ROOM_ID NVARCHAR2(50) UNIQUE,
DATE_FROM TIMESTAMP,
DATE_TO TIMESTAMP,
MONEY_PAID NUMERIC(15,2),
CONSTRAINT ID_CHECK CHECK (ID < 10000)
);