----hw1
ALTER TABLE EMPLOYEES
DROP (REPORTS_TO, NOTES, PHOTO);
----hw2
ALTER TABLE SUPPLIERS
DROP CONSTRAINT SUPPLIER_PK;

ALTER TABLE SUPPLIERS
ADD CONSTRAINT SUPPLIER_PK PRIMARY KEY (PHONE);
----hw3
ALTER TABLE CATEGORIES
ADD IS_ACTIVE NUMBER (0,1) NOT NULL;
----hw4
ALTER TABLE CATEGORIES
MODIFY PICTURE NVARCHAR2(100);
----hw5
CREATE MY_FIRST_SEQUENCE seq
MINVALUE 1
START WITH 1
INCREMENT BY 3
CACHE 20;
